import{developerDefinitions,sceneDefinitions,elementDefinitions,definitionKey,variantsFor,defaultVariant,variantFor,contractFor,resolveReviewEntity}from'./developer-d4-registry.js?v=D4-preview-contract';
const API={review:'./api/developer-d1',workspace:'./api/developer-d1-workspace',compare:'./api/developer-d1-comparisons'},KEY='yakolak:developer-d4:state:v1';
const STATUS={open:'جديدة',in_progress:'قيد التنفيذ',ready_for_review:'بانتظار قرارك',needs_changes:'تحتاج تعديل',approved:'معتمدة',rejected:'مرفوضة'},REQUEST={requested:'طلب جديد',in_review:'قيد المراجعة',accepted:'مقبول',implemented:'تمت إضافته',rejected:'مرفوض'},ROLE={reviewer:'ملاحظتك',developer:'رد المطور',system:'النظام'};
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)],esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),uuid=p=>`${p}:${crypto.randomUUID()}`;
const state={entities:[],threads:[],requests:[],comparisons:[],board:null,remote:false};
const first=developerDefinitions.find(x=>x.id==='clean-entry')||developerDefinitions[0];let selection={type:'entity',definition:first,variantId:defaultVariant(first).id},filter='all',requestKind='scene',compareOpen=false,previewRun=0,previewTimer=0;
const target=()=>selection.type==='entity'?contractFor(selection.definition,selection.variantId,document.baseURI):null;
const entityName=d=>state.entities.find(x=>x.entityType===d.kind&&x.entityId===d.id)?.displayName||d.defaultName;
const resolved=t=>resolveReviewEntity(t.entityType,t.entityId),targetThreads=(t=target())=>t?state.threads.filter(x=>x.entityType===t.definition.kind&&x.entityId===t.reviewEntityId).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))):[];
const definitionThreads=d=>state.threads.filter(x=>resolved(x)?.definition===d),latest=t=>[...(t.comments||[])].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0]||null;
const statusOf=threads=>{for(const s of['ready_for_review','needs_changes','in_progress','open'])if(threads.some(x=>x.status===s))return s;if(threads.length&&threads.every(x=>x.status==='approved'))return'approved';if(threads.some(x=>x.status==='rejected'))return'rejected';return''};
const saveLocal=()=>{try{localStorage.setItem(KEY,JSON.stringify({...state,savedAt:new Date().toISOString()}))}catch{}},readLocal=()=>{try{return JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('yakolak:developer-d3:state:v1')||'{}')}catch{return{}}};
async function json(url,options={}){const r=await fetch(url,{cache:'no-store',...options});if(!r.ok)throw Error(`${url}_${r.status}`);const data=await r.json();if(!data?.ok)throw Error(data?.error||'invalid_response');return data}const post=(url,body)=>json(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
function toast(text){const n=$('#d4Toast');n.textContent=text;n.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove('show'),2200)}
function sync(text,tone=''){state.remote=tone==='ok'||state.remote;$('#d4SyncText').textContent=text;$('#d4SyncDot').className=`d4-sync-dot${tone?` ${tone}`:''}`}
function title(d,v){return variantsFor(d).length>1?`${entityName(d)} · ${v.name}`:entityName(d)}
function queue(){const out=[];state.threads.forEach(thread=>{if(['approved','rejected'].includes(thread.status))return;const r=resolved(thread);if(r)out.push({type:'thread',status:thread.status,updatedAt:thread.updatedAt,title:title(r.definition,r.variant),subtitle:latest(thread)?.body||thread.title||'ملاحظة',definition:r.definition,variantId:r.variant.id})});state.requests.forEach(request=>{if(!['implemented','rejected'].includes(request.status))out.push({type:'request',status:request.status,updatedAt:request.updatedAt,title:request.title,subtitle:request.description||'طلب تطوير',request})});const rank={ready_for_review:0,needs_changes:1,requested:2,in_review:3,accepted:4,in_progress:5,open:6};return out.sort((a,b)=>(rank[a.status]??9)-(rank[b.status]??9)||String(b.updatedAt).localeCompare(String(a.updatedAt)))}
function mobile(view){$('#d4App').dataset.mobileView=view;$$('[data-mobile-view]').forEach(b=>b.classList.toggle('active',b.dataset.mobileView===view));if(view==='work')openDrawer('review');if(view==='content')closeDrawer()}
function nav(){const root=$('#d4NavList'),q=$('#d4Search').value.trim().toLowerCase();root.innerHTML='';$$('.d4-filter-row [data-filter]').forEach(b=>{const a=b.dataset.filter===filter;b.classList.toggle('active',a);b.setAttribute('aria-selected',String(a))});if(filter==='queue'){const items=queue().filter(x=>`${x.title} ${x.subtitle}`.toLowerCase().includes(q));$('#d4NavCount').textContent=`${items.length} مطلوب`;items.forEach(x=>root.append(queueNode(x)));if(!items.length)root.innerHTML='<div class="d4-empty">لا توجد أعمال مطلوبة الآن.</div>';return}const items=developerDefinitions.filter(x=>(filter==='all'||x.kind===filter)&&`${entityName(x)} ${x.description} ${x.sourceKey} ${x.journey}`.toLowerCase().includes(q));$('#d4NavCount').textContent=`${items.length} عنصر`;for(const[k,label]of[['scene','المشاهد والرحلات'],['element','العناصر']]){const group=items.filter(x=>x.kind===k);if(!group.length)continue;const h=document.createElement('div');h.className='d4-group-label';h.textContent=label;root.append(h);group.forEach(x=>root.append(entityNode(x)))}if(!items.length)root.innerHTML='<div class="d4-empty">لا توجد نتيجة مطابقة.</div>'}
function entityNode(d){const s=statusOf(definitionThreads(d)),b=document.createElement('button');b.type='button';b.className='d4-nav-item'+(selection.type==='entity'&&definitionKey(selection.definition)===definitionKey(d)?' active':'');b.innerHTML=`<span class="d4-nav-mark">${esc(d.mark)}</span><span class="d4-nav-copy"><strong>${esc(entityName(d))}</strong><span>${esc(d.description)}</span></span><span class="d4-nav-meta"><i class="d4-state-dot ${esc(s)}"></i>${esc(s?STATUS[s]:'')}</span>`;b.onclick=()=>selectEntity(d);return b}
function queueNode(x){const b=document.createElement('button');b.type='button';b.className='d4-nav-item';b.innerHTML=`<span class="d4-nav-mark">${x.type==='request'?'＋':esc(x.definition.mark)}</span><span class="d4-nav-copy"><strong>${esc(x.title)}</strong><span>${esc(x.subtitle)}</span></span><span class="d4-nav-meta"><i class="d4-state-dot ${esc(x.status)}"></i>${esc(x.type==='thread'?STATUS[x.status]:REQUEST[x.status])}</span>`;b.onclick=()=>x.type==='thread'?selectEntity(x.definition,{variantId:x.variantId,review:true}):selectRequest(x.request);return b}
function hash(){if(selection.type!=='entity')return;const p=new URLSearchParams();p.set(selection.definition.kind,selection.definition.id);p.set('variant',selection.variantId);history.replaceState(null,'',`#${p}`)}
function selectEntity(definition,{variantId=defaultVariant(definition).id,review=false}={}){selection={type:'entity',definition,variantId:variantFor(definition,variantId).id};setCompare(false);preview();render();hash();mobile('preview');if(review)openDrawer('review')}
function selectRequest(request){selection={type:'request',request};setCompare(false);render();mobile('work');openDrawer('review')}
function previewState(error=''){const n=$('#d4PreviewState');n.classList.remove('hidden');n.innerHTML=error?`<strong>${esc(error)}</strong><small>أعد المحاولة.</small><button class="d4-button ghost">إعادة المحاولة</button>`:'<span class="d4-spinner"></span><strong>جارٍ تجهيز المعاينة</strong><small>نحمّل النسخة المختارة فقط.</small>';n.querySelector('button')?.addEventListener('click',preview)}
function preview(){if(selection.type!=='entity')return;clearTimeout(previewTimer);previewState();const url=new URL(target().previewUrl);url.searchParams.set('reload',String(++previewRun));const f=$('#d4PreviewFrame');f.onerror=()=>previewState('تعذر تحميل المعاينة');f.src=url;previewTimer=setTimeout(()=>previewState('استغرقت المعاينة وقتًا أطول من المتوقع'),25000)}
function variantControl(t){const field=$('#d4VariantField'),select=$('#d4VariantSelect'),items=variantsFor(t.definition);field.hidden=items.length<=1;select.innerHTML=items.map(v=>`<option value="${esc(v.id)}">${esc(v.name)}</option>`).join('');select.value=t.variant.id;$('#d4VariantDescription').textContent=t.variant.description}
function render(){nav();$('#d4Coverage').textContent=`${sceneDefinitions.length} مشهد وحالة · ${elementDefinitions.length} عنصر`;if(selection.type==='request')return renderRequest();const t=target(),threads=targetThreads(t),s=statusOf(threads),ready=threads.filter(x=>x.status==='ready_for_review').length;variantControl(t);$('#d4SelectionKind').textContent=t.definition.label;$('#d4SelectionTitle').textContent=entityName(t.definition);$('#d4SelectionCode').textContent=`${t.definition.sourceKey} · ${t.variant.id}`;$('#d4SelectionStatus').textContent=s?STATUS[s]:'لا توجد ملاحظات';$('#d4SelectionStatus').className=`d4-status ${s||'neutral'}`;$('#d4ContextDescription').textContent=t.variant.description||t.definition.description;$('#d4ReviewHint').textContent=ready?`${ready} نتيجة تنتظر قرارك`:threads.some(x=>!['approved','rejected'].includes(x.status))?'يوجد عمل جارٍ على هذه النسخة':'لا توجد مراجعة تنتظر قرارك';$('#d4DrawerContext').textContent=title(t.definition,t.variant);for(const id of['#d4Replay','#d4CompareToggle','#d4Fullscreen'])$(id).disabled=false;reviewPanel();brief();comparison();counts()}
function renderRequest(){const r=selection.request;$('#d4VariantField').hidden=true;$('#d4SelectionKind').textContent=r.kind==='scene'?'طلب مشهد':'طلب عنصر';$('#d4SelectionTitle').textContent=r.title;$('#d4SelectionCode').textContent=`request:${r.id}`;$('#d4SelectionStatus').textContent=REQUEST[r.status]||r.status;$('#d4SelectionStatus').className=`d4-status ${r.status}`;$('#d4ContextDescription').textContent=r.description||'لا يوجد وصف.';$('#d4ReviewHint').textContent='راجع الطلب وردود التنفيذ';$('#d4DrawerContext').textContent=r.title;$('#d4PreviewFrame').src='about:blank';previewState('هذا طلب تطوير جديد');for(const id of['#d4Replay','#d4CompareToggle','#d4Fullscreen'])$(id).disabled=true;reviewPanel();brief();counts()}
function counts(){const n=queue().length;for(const id of['#d4QueueCount','#d4MobileCount']){$(id).textContent=n;$(id).hidden=!n}$('#d4DrawerReviewCount').textContent=selection.type==='entity'?targetThreads().filter(x=>!['approved','rejected'].includes(x.status)).length:(selection.request?.comments||[]).length}
function openDrawer(tab='task'){$('#d4DrawerScrim').hidden=false;$('#d4Drawer').classList.add('open');$('#d4Drawer').setAttribute('aria-hidden','false');setTab(tab)}function closeDrawer(){$('#d4DrawerScrim').hidden=true;$('#d4Drawer').classList.remove('open');$('#d4Drawer').setAttribute('aria-hidden','true')}
function setTab(tab){$$('[data-drawer-tab]').forEach(b=>{const a=b.dataset.drawerTab===tab;b.classList.toggle('active',a);b.setAttribute('aria-selected',String(a))});$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==tab);const t={task:['مهمة تطوير','اطلب تعديلًا'],review:['سجل العمل','المراجعة والقرار'],brief:['جسر الذكاء','أمر التنفيذ']}[tab];$('#d4DrawerKicker').textContent=t[0];$('#d4DrawerTitle').textContent=t[1];if(tab==='review')reviewPanel();if(tab==='brief')brief()}
function taskBody(){const evidence=$$('.d4-evidence-options input:checked').map(x=>({desktop:'صورة كمبيوتر',mobile:'صورة جوال',functional:'اختبار وظيفي',accessibility:'فحص وصول'}[x.value]));return[`المشكلة الحالية:\n${$('#d4TaskProblem').value.trim()}`,`النتيجة المطلوبة:\n${$('#d4TaskOutcome').value.trim()}`,`معايير القبول:\n${$('#d4TaskCriteria').value.trim()}`,`الدليل المطلوب:\n- ${evidence.join('\n- ')}`].join('\n\n')}
function briefText(){if(selection.type==='request'){const r=selection.request;return`نفّذ طلب ياكلك التالي كتغيير محدود:\n- النوع: ${r.kind}\n- الاسم: ${r.title}\n- الوصف: ${r.description||'—'}\n- مكانه: ${r.scenario||'غير محدد'}\nاختبره واترك الاعتماد للبشر.`}const t=target();return`أنت المطور الذكي لمنصة ياكلك. نفّذ أقل تغيير يحقق المهمة دون كسر اللعبة.\n\nالعقد:\n- النوع: ${t.definition.label}\n- الاسم: ${entityName(t.definition)}\n- النسخة: ${t.variant.name} (${t.variant.id})\n- المصدر: ${t.definition.sourceKey}\n- مفتاح المراجعة: ${t.reviewKey}\n- مفتاح المقارنة: ${t.comparisonKey}\n- رابط المعاينة: ${t.previewUrl}\n\n${taskBody()}\n\nتحقق على الكمبيوتر والجوال، بلا Console errors أو تجاوز أفقي، وبأهداف لمس 44px+، ولا تعتمد أو تنشر بدل المراجع البشري.`}function brief(){$('#d4BriefText').value=briefText()}
async function saveTask(e){e.preventDefault();if(selection.type!=='entity')return;const t=target();try{const data=await post(API.review,{action:'create_thread',threadId:uuid('thread'),commentId:uuid('comment'),entityType:t.definition.kind,entityId:t.reviewEntityId,authorRole:'reviewer',body:taskBody(),title:$('#d4TaskOutcome').value.trim().split('\n')[0].slice(0,100)});replaceThread(data.thread);$('#d4TaskForm').reset();$$('.d4-evidence-options input').forEach(x=>x.checked=true);setTab('review');toast('تم حفظ المهمة وربطها بهذه النسخة')}catch(error){console.error(error);toast('تعذر حفظ المهمة')}}
function reviewPanel(){const root=$('#d4ThreadList');root.innerHTML='';if(selection.type==='request')return requestReview(root);const threads=targetThreads(),active=threads.filter(x=>!['approved','rejected'].includes(x.status)),ready=threads.filter(x=>x.status==='ready_for_review').length;$('#d4ReviewSummary').innerHTML=`<span class="d4-review-chip">${threads.length} إجمالي</span><span class="d4-review-chip">${active.length} نشطة</span><span class="d4-review-chip">${ready} تنتظر قرارك</span>`;if(!threads.length){root.innerHTML='<div class="d4-empty">لا توجد مهام مرتبطة بهذه النسخة.</div>';return}threads.forEach(x=>root.append(threadNode(x)))}
function threadNode(thread){const comments=[...(thread.comments||[])].sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt))),last=comments.at(-1),a=document.createElement('article');a.className='d4-thread';a.dataset.threadId=thread.id;a.innerHTML=`<header><div class="d4-thread-title"><strong>${esc(thread.title||'مهمة')}</strong><span>${comments.length} رسائل</span></div><span class="d4-status ${esc(thread.status)}">${esc(STATUS[thread.status]||thread.status)}</span></header><div class="d4-thread-body">${last?comment(last):''}<details><summary>عرض السجل الكامل</summary><div class="d4-timeline">${comments.map(comment).join('')}</div></details><textarea maxlength="12000" placeholder="اكتب تعقيبًا واضحًا…"></textarea><div class="d4-thread-actions">${actions(thread.status)}</div></div>`;a.querySelectorAll('[data-thread-action]').forEach(b=>b.onclick=()=>threadAction(a,b.dataset.threadAction));return a}
const comment=c=>`<article class="d4-latest ${esc(c.authorRole||'reviewer')}"><small><span>${esc(ROLE[c.authorRole]||c.authorRole)}</span></small><p>${esc(c.body)}</p></article>`;
function actions(s){if(s==='ready_for_review')return'<button class="d4-action approve" data-thread-action="approved">اعتماد النتيجة</button><button class="d4-action changes" data-thread-action="needs_changes">تحتاج تعديل</button>';if(s==='needs_changes')return'<button class="d4-action primary" data-thread-action="reply-reviewer">إرسال التوضيح</button><button class="d4-action" data-thread-action="in_progress">بدأ التنفيذ</button>';return'<button class="d4-action primary" data-thread-action="reply-reviewer">إضافة تعقيب</button><button class="d4-action" data-thread-action="ready_for_review">جاهز للمراجعة</button>'}
async function threadAction(card,action){const input=card.querySelector('textarea'),text=input.value.trim(),threadId=card.dataset.threadId;let body;if(action==='reply-reviewer'){if(!text)return input.focus();body={action:'add_comment',threadId,commentId:uuid('comment'),authorRole:'reviewer',kind:'reply',body:text}}else{if(action==='needs_changes'&&!text)return input.focus();body={action:'set_status',threadId,status:action,commentId:uuid('comment'),authorRole:['in_progress','ready_for_review'].includes(action)?'developer':'reviewer',body:text||({approved:'تم اعتماد النتيجة.',needs_changes:'تحتاج النتيجة إلى تعديل.',in_progress:'بدأ التنفيذ.',ready_for_review:'جاهز للمراجعة.'}[action])}}try{const data=await post(API.review,body);replaceThread(data.thread)}catch(error){console.error(error);toast('تعذر حفظ التحديث')}}function replaceThread(thread){const i=state.threads.findIndex(x=>x.id===thread.id);if(i>=0)state.threads[i]=thread;else state.threads.unshift(thread);saveLocal();render()}
function requestReview(root){const r=selection.request,comments=r.comments||[];$('#d4ReviewSummary').innerHTML=`<span class="d4-review-chip">${esc(REQUEST[r.status]||r.status)}</span><span class="d4-review-chip">${comments.length} ردود</span>`;root.innerHTML=`<article class="d4-thread"><div class="d4-thread-body"><article class="d4-latest"><p>${esc(r.description||'لا يوجد وصف')}</p></article><div class="d4-timeline">${comments.map(comment).join('')}</div><textarea placeholder="اكتب تعقيبًا…"></textarea><div class="d4-thread-actions"><button class="d4-action primary" data-request-action="reply-reviewer">تعقيب</button><button class="d4-action" data-request-action="in_review">قيد المراجعة</button><button class="d4-action approve" data-request-action="accepted">قبول</button><button class="d4-action approve" data-request-action="implemented">تمت إضافته</button><button class="d4-action reject" data-request-action="rejected">رفض</button></div></div></article>`;root.querySelectorAll('[data-request-action]').forEach(b=>b.onclick=()=>requestAction(root,b.dataset.requestAction))}
async function requestAction(root,action){const text=root.querySelector('textarea').value.trim(),r=selection.request;try{const data=await post(API.workspace,action==='reply-reviewer'?{action:'request_comment',requestId:Number(r.id),commentId:uuid('request-comment'),authorRole:'reviewer',body:text}:{action:'request_status',requestId:Number(r.id),status:action});replaceRequest(data.request)}catch(error){console.error(error);toast('تعذر تحديث الطلب')}}function replaceRequest(r){const i=state.requests.findIndex(x=>Number(x.id)===Number(r.id));if(i>=0)state.requests[i]=r;else state.requests.unshift(r);if(selection.type==='request'&&Number(selection.request.id)===Number(r.id))selection.request=r;saveLocal();render()}
function setCompare(open){compareOpen=open;$('#d4CompareToggle').setAttribute('aria-pressed',String(open));$('#d4CompareView').hidden=!open;$('#d4LiveView').hidden=open;if(open)compareFrames()}const normal=v=>{try{const u=new URL(String(v||'').trim(),document.baseURI);return['http:','https;'].includes(u.protocol)?u.toString():''}catch{return''}};
function comparison(){if(selection.type!=='entity')return;const t=target(),saved=state.comparisons.find(x=>x.itemKey===t.comparisonKey);$('#d4BeforeUrl').value=saved?.beforeUrl||'';$('#d4AfterUrl').value=saved?.afterUrl||t.previewUrl;$('#d4CompareMessage').textContent=state.remote?'الحفظ مشترك':'الحفظ المحلي متاح';if(compareOpen)compareFrames()}function frame(f,e,v){const u=normal(v);$(e).hidden=!!u;$(f).src=u||'about:blank'}function compareFrames(){frame('#d4BeforeFrame','#d4BeforeEmpty',$('#d4BeforeUrl').value);frame('#d4AfterFrame','#d4AfterEmpty',$('#d4AfterUrl').value)}
async function saveComparison(){const t=target(),item={itemKey:t.comparisonKey,itemKind:'entity',beforeUrl:normal($('#d4BeforeUrl').value),afterUrl:normal($('#d4AfterUrl').value),updatedAt:new Date().toISOString()},i=state.comparisons.findIndex(x=>x.itemKey===item.itemKey);if(i>=0)state.comparisons[i]=item;else state.comparisons.push(item);saveLocal();try{const data=await post(API.compare,{action:'save',...item});state.comparisons[state.comparisons.findIndex(x=>x.itemKey===item.itemKey)]=data.comparison;state.remote=true;saveLocal();toast('تم حفظ المقارنة')}catch{toast('حُفظت المقارنة محليًا')}}
function modal(open){$('#d4ModalScrim').hidden=!open;$('#d4RequestModal').hidden=!open;if(open){requestKind='scene';$('#d4RequestForm').reset();requestAnimationFrame(()=>$('#d4RequestName').focus())}}async function submitRequest(e){e.preventDefault();try{const data=await post(API.workspace,{action:'request_create',kind:requestKind,title:$('#d4RequestName').value.trim(),description:$('#d4RequestDescription').value.trim(),scenario:$('#d4RequestScenario').value.trim()});replaceRequest(data.request);modal(false);filter='queue';selectRequest(data.request)}catch(error){console.error(error);toast('تعذر حفظ الطلب')}}
function utility(kind){const box=$('#d4Utility'),f=$('#d4UtilityFrame');box.hidden=false;if(kind==='game'){f.src='./';return}const cards=sceneDefinitions.map(x=>`<article><strong>${esc(entityName(x))}</strong><small>${esc(x.journey)}</small></article>`).join('');f.srcdoc=`<!doctype html><html lang="ar" dir="rtl"><style>*{box-sizing:border-box}body{margin:0;padding:24px;background:#f4f4f0;font-family:system-ui;display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}article{padding:16px;border:1px solid #ddd;border-radius:14px;background:#fff}strong,small{display:block}small{margin-top:6px;color:#777}</style><body>${cards}</body></html>`}function utilityClose(){$('#d4Utility').hidden=true;$('#d4UtilityFrame').src='about:blank'}
function handleMessage(e){const f=$('#d4PreviewFrame'),data=e.data||{};if(e.source!==f.contentWindow||selection.type!=='entity')return;const t=target();if(data.entityId!==t.definition.id)return;if(data.type==='yakolak-developer-scene-error'){clearTimeout(previewTimer);return previewState(data.error||'فشلت المعاينة')}if(data.type!=='yakolak-developer-scene-ready'||(t.previewMode!=='base'&&data.build!=='D4')||(data.variant&&data.variant!==t.variant.id))return;clearTimeout(previewTimer);$('#d4PreviewState').classList.add('hidden')}
async function load(){sync('جارٍ المزامنة');const local=readLocal();for(const k of['entities','threads','requests','comparisons','board'])if(local[k])state[k]=local[k];render();try{const[a,b,c]=await Promise.all([json(API.review),json(API.workspace),json(API.compare)]);state.entities=a.entities||[];state.threads=a.threads||[];state.requests=b.requests||[];state.board=b.board||state.board;state.comparisons=c.comparisons||[];state.remote=true;saveLocal();sync('متصل','ok')}catch(error){console.warn('[Yakolak] D4 local fallback',error);sync('عرض محلي','warn')}render();document.body.dataset.developerBuild='D4-variant-workspace';document.body.dataset.developerReady='true'}
function restore(){const p=new URLSearchParams(location.hash.slice(1)),kind=p.has('element')?'element':p.has('scene')?'scene':'';const d=developerDefinitions.find(x=>x.kind===kind&&x.id===p.get(kind));if(d)selection={type:'entity',definition:d,variantId:variantFor(d,p.get('variant')).id}}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('تم النسخ')}catch{}}
function bind(){$$('.d4-filter-row [data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;nav()});$('#d4Search').oninput=nav;$('#d4OpenQueue').onclick=()=>{filter='queue';nav();mobile('content')};$('#d4MobileContent').onclick=()=>mobile('content');$('#d4VariantSelect').onchange=()=>selectEntity(selection.definition,{variantId:$('#d4VariantSelect').value});$('#d4Replay').onclick=preview;$('#d4RetryPreview').onclick=preview;$('#d4CompareToggle').onclick=()=>setCompare(!compareOpen);$('#d4Fullscreen').onclick=()=>$('#d4PreviewShell').requestFullscreen?.();$('#d4BeforeUrl').onchange=compareFrames;$('#d4AfterUrl').onchange=compareFrames;$('#d4UseCurrent').onclick=()=>{$('#d4AfterUrl').value=target().previewUrl;compareFrames()};$('#d4SaveCompare').onclick=saveComparison;$$('[data-open-compare]').forEach(b=>b.onclick=()=>{const u=normal(b.dataset.openCompare==='before'?$('#d4BeforeUrl').value:$('#d4AfterUrl').value);if(u)open(u,'_blank','noopener,noreferrer')});$('#d4StartTask').onclick=()=>openDrawer('task');$('#d4ReviewOpen').onclick=()=>openDrawer('review');$('#d4BriefOpen').onclick=()=>openDrawer('brief');$('#d4DrawerClose').onclick=closeDrawer;$('#d4DrawerScrim').onclick=closeDrawer;$$('[data-drawer-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.drawerTab));$('#d4TaskForm').onsubmit=saveTask;$('#d4CopyTask').onclick=()=>copy(briefText());$('#d4CopyBrief').onclick=()=>copy($('#d4BriefText').value);$('#d4RefreshBrief').onclick=brief;$('#d4NewRequest').onclick=()=>modal(true);$('#d4RequestClose').onclick=()=>modal(false);$('#d4ModalScrim').onclick=()=>modal(false);$$('[data-request-kind]').forEach(b=>b.onclick=()=>{requestKind=b.dataset.requestKind;$$('[data-request-kind]').forEach(x=>x.classList.toggle('active',x===b))});$('#d4RequestForm').onsubmit=submitRequest;$('#d4FlowOpen').onclick=()=>utility('flow');$('#d4GameOpen').onclick=()=>utility('game');$('#d4UtilityClose').onclick=utilityClose;$$('.d4-mobile-nav [data-mobile-view]').forEach(b=>b.onclick=()=>mobile(b.dataset.mobileView));addEventListener('message',handleMessage);addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#d4RequestModal').hidden)modal(false);else if(!$('#d4Utility').hidden)utilityClose();else closeDrawer()}if(e.target.matches('input,textarea,select'))return;if(e.key.toLowerCase()==='r'&&selection.type==='entity')preview();if(e.key.toLowerCase()==='c'&&selection.type==='entity')setCompare(!compareOpen)})}
restore();bind();preview();render();load();
