import * as THREE from 'three';
const baseAdd=THREE.Object3D.prototype.add;
let scene=null,done=false,rig=null,refs=[];
const KEY='yakolak_lights';
const DEF=[['A','#ffffff',1.8,1800,1.4,30,-520,380,430],['B','#fff2cf',1.1,1600,1.5,26,520,300,360],['C','#d8ecff',.9,1500,1.4,24,0,850,-360]];
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||DEF}catch(e){return DEF}};
const write=v=>{try{localStorage.setItem(KEY,JSON.stringify(v))}catch(e){}};
const redraw=()=>requestAnimationFrame(()=>window.dispatchEvent(new Event('resize')));
function apply(data){refs.forEach((r,i)=>{const d=data[i];if(!d)return;const c=new THREE.Color(d[1]);r.mesh.material.color.copy(c);r.light.color.copy(c);r.light.intensity=+d[2];r.light.distance=+d[3];r.light.decay=+d[4];r.mesh.scale.setScalar(+d[5]/24);r.mesh.position.set(+d[6],+d[7],+d[8]);r.light.position.copy(r.mesh.position);r.mesh.visible=r.light.visible=+d[2]>0})}
function copyText(text,btn){if(navigator.clipboard){navigator.clipboard.writeText(text).then(()=>btn.textContent='تم النسخ ✅').catch(()=>fallback(text,btn))}else fallback(text,btn)}
function fallback(text,btn){const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();btn.textContent='تم النسخ ✅'}
function panel(data){const p=document.createElement('div');p.style.cssText='position:fixed;right:12px;top:12px;z-index:10001;width:260px;max-height:88vh;overflow:auto;background:#111;color:#fff;border:1px solid #555;border-radius:12px;padding:10px;font:12px system-ui;direction:rtl';p.innerHTML='<b>Light Orbs</b><br><small>Original lights off</small>';const names=['','Color','Power','Range','Decay','Size','X','Y','Z'];data.forEach((d,i)=>{const box=document.createElement('div');box.style.cssText='border-top:1px solid #333;margin-top:8px;padding-top:8px';box.innerHTML='<b>Orb '+d[0]+'</b>';for(let k=1;k<d.length;k++){const lab=document.createElement('label');lab.style.cssText='display:grid;grid-template-columns:55px 1fr 42px;gap:5px;margin:5px 0;align-items:center';const inp=document.createElement('input');inp.type=k===1?'color':'range';if(k>1){const r=[[0,8,.05],[100,5000,50],[0,3,.05],[8,90,1],[-1500,1500,10],[-650,1400,10],[-1500,1500,10]][k-2];inp.min=r[0];inp.max=r[1];inp.step=r[2]}inp.value=d[k];const out=document.createElement('span');out.textContent=d[k];inp.oninput=()=>{d[k]=k===1?inp.value:+inp.value;out.textContent=d[k];apply(data);write(data);redraw()};lab.append(names[k],inp,out);box.appendChild(lab)}p.appendChild(box)});const b=document.createElement('button');b.textContent='نسخ القيم';b.style.cssText='width:100%;margin-top:10px;border:0;border-radius:10px;padding:9px;background:#fff;color:#000;font-weight:800;cursor:pointer';b.onclick=()=>copyText('YAKOLAK_LIGHTS='+JSON.stringify(data),b);p.appendChild(b);document.body.appendChild(p)}
function build(){if(!scene||rig)return;const data=read();rig=new THREE.Group();rig.name='yakolak-orb-light-rig';refs=data.map(d=>{const mesh=new THREE.Mesh(new THREE.SphereGeometry(24,24,16),new THREE.MeshBasicMaterial({color:d[1]}));const light=new THREE.PointLight(d[1],d[2],d[3],d[4]);light.userData.orbLight=true;baseAdd.call(rig,mesh);baseAdd.call(rig,light);return {mesh,light}});baseAdd.call(scene,rig);panel(data);apply(data);redraw()}
THREE.Object3D.prototype.add=function(...items){if(this.isScene){scene=this;if(!done){done=true;setTimeout(build,120)}}items.forEach(o=>{if(o&&o.isLight&&!o.userData.orbLight){o.intensity=0;o.visible=false}});return baseAdd.apply(this,items)};
