import * as THREE from 'three';
const baseAdd=THREE.Object3D.prototype.add;
let scene=null,done=false,rig=null,refs=[];
const KEY='yakolak_lights';
const DEF=[['A','#ffffff',1.8,1800,1.4,30,-520,380,430],['B','#fff2cf',1.1,1600,1.5,26,520,300,360],['C','#d8ecff',.9,1500,1.4,24,0,850,-360]];
const F=['name','color','power','range','decay','size','x','y','z'];
const STEP={power:.05,range:50,decay:.05,size:1,x:10,y:10,z:10};
const AR={color:'اللون',power:'القوة',range:'المدى',decay:'التلاشي',size:'الحجم',x:'يمين/يسار',y:'الارتفاع',z:'العمق'};
const clone=v=>JSON.parse(JSON.stringify(v));
const read=()=>{try{const v=JSON.parse(localStorage.getItem(KEY));return Array.isArray(v)?v:clone(DEF)}catch(e){return clone(DEF)}};
const write=v=>{try{localStorage.setItem(KEY,JSON.stringify(v))}catch(e){}};
const redraw=()=>requestAnimationFrame(()=>window.dispatchEvent(new Event('resize')));
const num=v=>Number(Number(v).toFixed(3));
function idx(k){return F.indexOf(k)}
function makeLabel(txt){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.fillStyle='rgba(0,0,0,.72)';x.beginPath();x.arc(64,64,46,0,Math.PI*2);x.fill();x.strokeStyle='white';x.lineWidth=6;x.stroke();x.fillStyle='white';x.font='900 56px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(txt,64,66);const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;const sp=new THREE.Sprite(new THREE.SpriteMaterial({map,transparent:true,depthTest:false,depthWrite:false}));sp.scale.set(34,34,1);sp.position.set(0,42,0);sp.renderOrder=10000;return sp}
function apply(data){refs.forEach((r,i)=>{const d=data[i];if(!d)return;const c=new THREE.Color(d[1]);r.mesh.material.color.copy(c);r.halo.material.color.copy(c);r.light.color.copy(c);r.light.intensity=+d[2];r.light.distance=+d[3];r.light.decay=+d[4];r.mesh.scale.setScalar(+d[5]/24);r.halo.scale.setScalar(+d[5]/24);r.group.position.set(+d[6],+d[7],+d[8]);r.group.visible=+d[2]!==0})}
function copyText(text,btn){if(navigator.clipboard){navigator.clipboard.writeText(text).then(()=>btn.textContent='تم النسخ ✅').catch(()=>fallback(text,btn))}else fallback(text,btn)}
function fallback(text,btn){const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();btn.textContent='تم النسخ ✅'}
function openButton(){let b=document.getElementById('gptLightOpen');if(b)return b;b=document.createElement('button');b.id='gptLightOpen';b.textContent='معايرة الإضاءة';b.style.cssText='position:fixed;right:12px;bottom:12px;z-index:10002;border:0;border-radius:999px;padding:12px 16px;background:#fff;color:#000;font:900 13px system-ui;box-shadow:0 10px 28px #0008;cursor:pointer';document.body.appendChild(b);return b}
function panel(data){document.getElementById('gptLightPanel')?.remove();const p=document.createElement('div');p.id='gptLightPanel';p.style.cssText='position:fixed;right:12px;top:12px;z-index:10001;width:320px;max-height:88vh;overflow:auto;background:rgba(14,14,14,.94);color:#fff;border:1px solid #444;border-radius:16px;padding:12px;font:12px system-ui;direction:rtl;box-shadow:0 16px 40px #0008';p.innerHTML='<div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><b style="font-size:15px">معايرة كور الإضاءة</b><button id="hidePanel" style="border:1px solid #555;background:#222;color:#fff;border-radius:10px;padding:6px 10px;cursor:pointer">إخفاء</button></div><div style="opacity:.75;margin:6px 0 10px">كل القيم مفتوحة بلا حدود: رقم يدوي + ناقص + زائد.</div>';p.querySelector('#hidePanel').onclick=()=>p.style.display='none';
 const row=(d,k)=>{const id=idx(k),step=STEP[k],wrap=document.createElement('div');wrap.style.cssText='display:grid;grid-template-columns:72px 32px 1fr 32px;gap:6px;align-items:center;margin:7px 0';const name=document.createElement('span');name.textContent=AR[k];const minus=document.createElement('button');minus.textContent='−';const plus=document.createElement('button');plus.textContent='+';[minus,plus].forEach(b=>b.style.cssText='height:32px;border:1px solid #444;border-radius:10px;background:#222;color:#fff;font-weight:900;cursor:pointer');const input=document.createElement('input');input.type='number';input.step=step;input.value=d[id];input.style.cssText='height:32px;border:1px solid #444;border-radius:10px;background:#050505;color:#fff;text-align:center';const setv=v=>{const n=Number(v);if(!Number.isFinite(n))return;d[id]=num(n);input.value=d[id];apply(data);write(data);redraw()};minus.onclick=()=>setv((+input.value||0)-step);plus.onclick=()=>setv((+input.value||0)+step);input.oninput=()=>setv(input.value);wrap.append(name,minus,input,plus);return wrap};
 data.forEach((d,i)=>{const box=document.createElement('div');box.style.cssText='border-top:1px solid #333;margin-top:10px;padding-top:10px';box.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center"><b>الكورة '+(i+1)+' — '+d[0]+'</b><span style="opacity:.6">'+d[1]+'</span></div>';const color=document.createElement('label');color.style.cssText='display:grid;grid-template-columns:72px 1fr;gap:6px;align-items:center;margin:8px 0';color.innerHTML='<span>اللون</span><input type="color" value="'+d[1]+'" style="width:100%;height:34px;border:0;background:transparent">';color.querySelector('input').oninput=e=>{d[1]=e.target.value;apply(data);write(data);redraw()};box.appendChild(color);['power','range','decay','size','x','y','z'].forEach(k=>box.appendChild(row(d,k)));p.appendChild(box)});
 const actions=document.createElement('div');actions.style.cssText='display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px';const copy=document.createElement('button');copy.textContent='نسخ القيم';const reset=document.createElement('button');reset.textContent='افتراضي';[copy,reset].forEach(b=>b.style.cssText='border:0;border-radius:12px;padding:10px;background:#fff;color:#000;font-weight:900;cursor:pointer');copy.onclick=()=>copyText('YAKOLAK_LIGHTS='+JSON.stringify(data),copy);reset.onclick=()=>{localStorage.removeItem(KEY);location.reload()};actions.append(copy,reset);p.appendChild(actions);document.body.appendChild(p);openButton().onclick=()=>{p.style.display='block'}}
function build(){if(!scene||rig)return;const data=read();rig=new THREE.Group();rig.name='yakolak-orb-light-rig';refs=data.map((d,i)=>{const group=new THREE.Group();group.name='yakolak-orb-'+(i+1);const mesh=new THREE.Mesh(new THREE.SphereGeometry(24,32,20),new THREE.MeshBasicMaterial({color:d[1],depthTest:false,depthWrite:false}));const halo=new THREE.Mesh(new THREE.SphereGeometry(48,32,20),new THREE.MeshBasicMaterial({color:d[1],transparent:true,opacity:.28,depthTest:false,depthWrite:false}));const light=new THREE.PointLight(d[1],d[2],d[3],d[4]);light.userData.orbLight=true;mesh.renderOrder=9999;halo.renderOrder=9998;baseAdd.call(group,light);baseAdd.call(group,halo);baseAdd.call(group,mesh);baseAdd.call(group,makeLabel(String(i+1)));baseAdd.call(rig,group);return {group,mesh,halo,light}});baseAdd.call(scene,rig);panel(data);apply(data);redraw()}
THREE.Object3D.prototype.add=function(...items){if(this.isScene){scene=this;if(!done){done=true;setTimeout(build,120)}}items.forEach(o=>{if(o&&o.isLight&&!o.userData.orbLight){o.intensity=0;o.visible=false}});return baseAdd.apply(this,items)};
